DROP TABLE IF EXISTS hw6_games CASCADE;
DROP TABLE IF EXISTS hw6_users CASCADE;
DROP TABLE IF EXISTS hw6_words CASCADE;

CREATE TABLE hw6_users (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL
);

CREATE TABLE hw6_games (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES hw6_users(id),
  target_word TEXT NOT NULL,
  score INTEGER DEFAULT 0,
  won BOOLEAN DEFAULT FALSE,
  date_started TIMESTAMP DEFAULT NOW(),
  date_finished TIMESTAMP
);

CREATE TABLE hw6_words (
  word TEXT PRIMARY KEY
);
